BOT:
  token: "empty-as-my-soul"
  prefix: "yuno "
  activity: "LISTENING"
  activityMessage: "oki boomer (1 hour perfect loop)"
  status: "DO_NOT_DISTURB"

EVENTS:
  joinLeave:
    channel: "testing-chamber"

DATABASE:
  type: "sqlite"
  hostname: "localhost"
  port: "3306"
  database: "yuno"
  username: "yuno"
  password: "password"